targets:
  $default:
    builders:
      freezed|freezed:
        generate_for:
          - "lib/src/actions/**.dart"
          - "lib/src/presentation/containers/**.dart"
          - "lib/src/models/**.dart"
        options:
          maybe_when: false
          maybe_map: false
      json_serializable:
        generate_for:
          - "lib/src/models/**.dart"